# Generated by Django 4.0.2 on 2022-02-11 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSetting',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('camera_type', models.CharField(blank=True, max_length=30, null=True)),
                ('iso', models.CharField(blank=True, max_length=10, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=10, null=True)),
                ('fps', models.IntegerField(blank=True, default=0, help_text='Frames per second', null=True)),
                ('lens_type', models.CharField(blank=True, max_length=20, null=True)),
                ('focal_length', models.CharField(blank=True, max_length=10, null=True)),
                ('aperture', models.CharField(blank=True, max_length=10, null=True)),
                ('question_field_one', models.TextField(blank=True, null=True)),
                ('question_field_two', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camera_setting',
            },
        ),
    ]
