# Generated by Django 4.0.2 on 2022-02-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_camerasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasetting',
            name='is_profile_camera_settings',
            field=models.BooleanField(default=True),
        ),
    ]
