# Generated by Django 4.0.2 on 2022-02-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='aperture',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='camerasetting',
            name='camera_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camerasetting',
            name='focal_length',
            field=models.CharField(max_length=10),
        ),
    ]
