# Generated by Django 4.0.2 on 2022-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_camerasetting_aperture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='fps',
            field=models.CharField(blank=True, help_text='Frames per second', max_length=10, null=True),
        ),
    ]
