# Generated by Django 4.0.2 on 2022-03-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_camerasetting_fps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='aperture',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='camerasetting',
            name='camera_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='camerasetting',
            name='focal_length',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
