# Generated by Django 4.0.2 on 2022-03-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_camerasetting_aperture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camerasetting',
            name='aperture',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
