# Generated by Django 4.0.2 on 2022-03-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_usercountryflag_user_country_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
