# Generated by Django 4.0.2 on 2022-04-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_usercountryflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
