# Generated by Django 4.0.2 on 2022-04-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_trained'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
