# Generated by Django 3.2.13 on 2022-05-13 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='article_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Blog'), (2, 'Tutorial')], default=1),
        ),
    ]
