# Generated by Django 3.2.13 on 2022-05-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_article_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='mp40blxs9dqr8g5a', max_length=500),
        ),
    ]
