# Generated by Django 4.0.2 on 2022-05-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogimagemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.FileField(upload_to='blog/blog_image')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='article_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Blog'), (2, 'Tutorial')], default=1),
        ),
        migrations.DeleteModel(
            name='BlogImageMapping',
        ),
    ]
