# Generated by Django 3.2.13 on 2022-05-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogimagedata_blog_article_type_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='blog',
        #     name='article_type',
        # ),
        # migrations.AddField(
        #     model_name='blog',
        #     name='category',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory'),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail_image',
            field=models.ImageField(default=1, upload_to='blog/thumbnail_image'),
            preserve_default=False,
        ),
    ]
