# Generated by Django 3.2.13 on 2022-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='mh723g4ep1bx00f7', max_length=500, null=True),
        ),
    ]
