# Generated by Django 3.2.13 on 2022-08-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contentmanagement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentmanagement',
            name='type',
            field=models.CharField(choices=[('policy', 'Spritacular Policy'), ('become-an-ambassador', 'Become an ambassador'), ('spritacular-google-group', 'Spritacular Google Group')], max_length=100),
        ),
    ]
