# Generated by Django 3.2.13 on 2022-08-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_meettheteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meettheteam',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
