# Generated by Django 3.2.13 on 2022-08-22 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_meettheteam_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meettheteam',
            old_name='description',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='meettheteam',
            old_name='image',
            new_name='thumbnail_image',
        ),
    ]
