# Generated by Django 3.2.13 on 2022-08-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20220822_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meettheteam',
            old_name='name',
            new_name='title',
        ),
    ]
