# Generated by Django 4.0.2 on 2022-02-23 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_camerasetting_aperture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=20, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('image_type', models.PositiveSmallIntegerField(choices=[(1, 'Single image'), (2, 'Multiple images from same or different observation.'), (3, 'Images sequence from video recorded.')], default=1)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_reject', models.BooleanField(default=False)),
                ('is_to_be_verify', models.BooleanField(default=False)),
                ('is_submit', models.BooleanField(default=False)),
                ('reject_message', models.TextField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.camerasetting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerifyObservation',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('vote', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.category')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verify_observation',
            },
        ),
        migrations.CreateModel(
            name='ObservationLike',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observation_like',
            },
        ),
        migrations.CreateModel(
            name='ObservationImageMapping',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('image', models.ImageField(upload_to='observation_image')),
                ('location', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=10)),
                ('obs_date', models.DateField()),
                ('obs_time', models.TimeField()),
                ('obs_date_time_as_per_utc', models.DateTimeField()),
                ('timezone', models.CharField(max_length=20)),
                ('azimuth', models.CharField(max_length=10)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObservationCategoryMapping',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.category')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observation')),
            ],
            options={
                'db_table': 'observation_category_mapping',
            },
        ),
    ]
