# Generated by Django 4.0.2 on 2022-02-28 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_camerasetting_aperture_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('observation', '0002_alter_observationimagemapping_obs_date_time_as_per_utc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.camerasetting'),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='azimuth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='obs_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='obs_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='timezone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='ObservationComment',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observation.observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observation_comment',
            },
        ),
    ]
