# Generated by Django 4.0.2 on 2022-03-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_camerasetting_aperture_and_more'),
        ('observation', '0003_alter_observation_camera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationimagemapping',
            name='is_precise_azimuth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observationimagemapping',
            name='time_accuracy',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.camerasetting'),
        ),
    ]
