# Generated by Django 4.0.2 on 2022-03-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0005_alter_observationimagemapping_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='elevation_angle',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='story',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='observation',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observationimagemapping',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='observationimagemapping',
            name='place_uid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='observationimagemapping',
            name='location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
