# Generated by Django 4.0.2 on 2022-03-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0006_observation_elevation_angle_observation_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationimagemapping',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
