# Generated by Django 4.0.2 on 2022-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0007_alter_observationimagemapping_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='observationimagemapping',
            name='compressed_image',
            field=models.ImageField(blank=True, null=True, upload_to='compressed_observation_image'),
        ),
    ]
