# Generated by Django 3.2.13 on 2022-07-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0013_observation_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='active_tab',
            field=models.JSONField(default=dict),
        ),
    ]
