# Generated by Django 3.2.13 on 2022-07-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observation', '0014_observation_active_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='media_file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
